// Stable server check identifiers map to translatable product labels.
export const evidenceLabels: Record<string, string> = {
  wallet_equals_available_minus_debt: "Wallet and funding balance",
  account_version: "Funding account version",
  money_seq: "Funding sequence",
  commission_balance_equation: "Commission balance conservation",
  withdrawal_snapshot: "Withdrawal snapshot",
  locked_equals_outstanding_withdrawals: "Locked funds and pending withdrawals",
  balance_version: "Commission balance version",
  paid_lot_conservation: "Paid funding conservation",
  bonus_lot_conservation: "Bonus funding conservation",
  lot_version: "Funding lot version",
  binding_user: "Assigned customer",
  binding_agency: "Assigned agency",
  binding_revision: "Assignment revision",
  binding_is_current: "Assignment is current",
  binding_id: "Assignment ID",
  operation_event_count: "Operation event count",
  operation_revision: "Operation revision",
  operation_money_seq: "Funding sequence",
  event_index: "Event sequence index",
  event_count: "Operation event count",
  event_id: "Event ID",
  outbox_payload_decodes: "Event data can be read",
  outbox_payload_hash: "Event content integrity",
  event_schema: "Event format version",
  stored_schema: "Stored format version",
  event_identity: "Event ID",
  event_operation: "Operation ID",
  event_user: "User ID",
  event_money_seq: "Funding sequence",
  event_amounts_valid: "Event amounts are valid",
  receipt_payload_hash: "Receipt content integrity",
  receipt_is_terminal: "Receipt processing is complete",
  delivery_exists: "Delivery record exists",
  delivery_id: "Delivery record ID",
  supported_invariant: "Automatic verification is supported",
  authoritative_source_exists: "Authoritative record exists",
  commission_reversal_within_earned: "Reversed commission does not exceed earnings",
  withdrawal_amount_positive: "Withdrawal amount is positive",
  operation_event_count_valid: "Event count is valid",
  operation_committed_result: "Committed operation result exists",
  operation_result_hash: "Operation result fingerprint",
  operation_result_format_supported: "Operation result format is supported",
  committed_event_id: "Committed event ID",
  committed_outbox_hash: "Committed event storage integrity",
  committed_payload_hash: "Committed event content integrity",
  receipt_journal_revision: "Operation revision",
  delivery_state: "Status",
  delivery_state_valid: "Delivery status is valid",
  done_delivery_has_receipt: "Completed delivery has a permanent receipt",
  source_event_identity: "Event ID",
  event_kind: "Event type",
  event_batch_valid: "Event sequence is valid",
  receipt_operation: "Operation ID",
  receipt_schema: "Event format version",
  receipt_user: "User ID",
  receipt_money_seq: "Funding sequence",
  earned_micros: "Earned commission",
  reversed_micros: "Reversed commission",
  paid_micros: "Paid commission",
  locked_micros: "Locked commission",
  paid_initial: "Initial paid funding",
  paid_available: "Available paid funding",
  paid_reserved: "Reserved paid funding",
  paid_consumed: "Consumed paid funding",
  paid_revoked: "Revoked paid funding",
  paid_debt_repaid: "Paid funding used to repay debt",
  bonus_initial: "Initial bonus funding",
  bonus_available: "Available bonus funding",
  bonus_reserved: "Reserved bonus funding",
  bonus_consumed: "Consumed bonus funding",
  bonus_revoked: "Revoked bonus funding",
  nonpaid_available: "Available nonpaid funding",
  debt_quota: "Outstanding funding debt",
};
